# Generated by Django 4.1.1 on 2022-10-21 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='shortsv2',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='shortsv2',
            name='video',
        ),
        migrations.AddField(
            model_name='categoriapost',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=100, verbose_name='color ategory'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Post likes'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Post likes counter'),
        ),
        migrations.AddField(
            model_name='shortsv2',
            name='user_answered',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answersforshortsv2',
            name='parent_question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.shortsv2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_src',
            field=models.URLField(default='http://127.0.0.1:8000/<django.db.models.fields.files.FileField>', verbose_name='post image source '),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, verbose_name='comment')),
                ('created_date', models.CharField(max_length=255)),
                ('approved_comment', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
