# Generated by Django 4.1.1 on 2022-10-22 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_post_intro_remove_shortsv2_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortsv2',
            name='user_answered',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
