# Generated by Django 4.1.1 on 2023-05-16 03:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_learnedcards"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learnedcards",
            old_name="cardLearned",
            new_name="card_learned",
        ),
    ]
