# Generated by Django 4.1.1 on 2022-10-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_shortsv2_user_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Category Cards')),
            ],
        ),
        migrations.AddField(
            model_name='cards',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoriacard'),
        ),
    ]
