# Generated by Django 4.1.1 on 2023-05-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_cardlearned_learnedcards_card_learned"),
    ]

    operations = [
        migrations.AddField(
            model_name="cards",
            name="is_learned",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Learned"
            ),
        ),
    ]
