# Generated by Django 4.1.1 on 2022-10-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_usermodel_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shortsv2',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='shorts', verbose_name='VideoFile'),
        ),
    ]
