# Generated by Django 3.2 on 2023-02-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_cards_cardsound"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cards",
            name="cardSound",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="sound src"
            ),
        ),
    ]
