# Generated by Django 4.1.1 on 2022-10-22 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_post_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cards',
            name='cardImage',
            field=models.ImageField(blank=True, null=True, upload_to='cards', verbose_name='Card image'),
        ),
    ]
