# Generated by Django 4.1.1 on 2022-10-22 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cards_owner_alter_cards_cardimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoriacard'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
