# Generated by Django 4.1.1 on 2022-10-23 02:13

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cards_categoria_alter_cards_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='file',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True),
        ),
    ]
