# Generated by Django 4.1.1 on 2022-10-23 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cards_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='file',
        ),
    ]
