# Generated by Django 4.1.1 on 2022-10-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_cards_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortsv2',
            name='video',
            field=models.FileField(null=True, upload_to='shorts', verbose_name='VideoFile'),
        ),
    ]
