# Generated by Django 3.2 on 2023-02-09 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_cards_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cards",
            options={"ordering": ["-id"]},
        ),
    ]
