# Generated by Django 4.1.1 on 2022-10-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_shortsv2_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='imageURL',
            field=models.URLField(blank=True, verbose_name='Image source'),
        ),
    ]
