# Generated by Django 4.1.1 on 2023-03-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cards_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacard',
            options={'verbose_name': 'Category Cards'},
        ),
        migrations.AlterModelOptions(
            name='categoriapost',
            options={'verbose_name': 'Category'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='utc',
            field=models.BooleanField(default=False, verbose_name='UTC alumno'),
        ),
    ]
