# Generated by Django 4.1.1 on 2023-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_categoriacard_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='utc',
        ),
    ]
