# Generated by Django 4.1.1 on 2023-04-19 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_remove_usermodel_utc"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerbsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "infinitive",
                    models.CharField(max_length=50, verbose_name="Infinitive"),
                ),
                ("past", models.CharField(max_length=50, verbose_name="past")),
                (
                    "participle",
                    models.CharField(max_length=50, verbose_name="participle"),
                ),
                ("spanish", models.CharField(max_length=50, verbose_name="spanish")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
