# Generated by Django 4.1.1 on 2023-04-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_verbsmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="verbsmodel",
            name="sound",
            field=models.TextField(default="", verbose_name="sound"),
        ),
    ]
