# Generated by Django 4.1.1 on 2023-04-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_verbsmodel_sound"),
    ]

    operations = [
        migrations.RenameField(
            model_name="verbsmodel",
            old_name="sound",
            new_name="inf_sound",
        ),
        migrations.AddField(
            model_name="verbsmodel",
            name="participle_sound",
            field=models.TextField(default="", verbose_name="sound"),
        ),
        migrations.AddField(
            model_name="verbsmodel",
            name="past_sound",
            field=models.TextField(default="", verbose_name="sound"),
        ),
    ]
