# Generated by Django 4.1.1 on 2023-04-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_rename_sound_verbsmodel_inf_sound_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verbsmodel",
            name="inf_sound",
            field=models.TextField(blank=True, default="", verbose_name="sound"),
        ),
        migrations.AlterField(
            model_name="verbsmodel",
            name="participle_sound",
            field=models.TextField(blank=True, default="", verbose_name="sound"),
        ),
        migrations.AlterField(
            model_name="verbsmodel",
            name="past_sound",
            field=models.TextField(blank=True, default="", verbose_name="sound"),
        ),
    ]
