# Generated by Django 4.1.1 on 2023-05-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_verbsmodel_inf_sound_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cards",
            name="image",
            field=models.TextField(blank=True, null=True, verbose_name="Image"),
        ),
    ]
