# Generated by Django 4.1.1 on 2023-05-04 03:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_cards_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cards",
            name="cardImage",
        ),
        migrations.RemoveField(
            model_name="cards",
            name="imageURL",
        ),
    ]
