# Generated by Django 4.1.1 on 2022-10-18 00:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_shortsv2_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortsv2',
            name='video',
        ),
        migrations.AddField(
            model_name='shortsv2',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
