# Generated by Django 4.1.1 on 2022-10-18 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_shortsv2_video_shortsv2_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortsv2',
            name='file',
        ),
    ]
