# Generated by Django 4.1.1 on 2022-10-20 20:10

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_shortsv2_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=markdownfield.models.MarkdownField(default='', rendered_field='text_rendered'),
        ),
    ]
