# Generated by Django 4.1.1 on 2022-10-20 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_answersforshortsv2_parent_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='shortsv2',
            name='user_answered',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
