# Generated by Django 4.0.6 on 2022-08-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cards_cardimage_alter_cards_cardmeaning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='cardImage',
            field=models.ImageField(upload_to='cards', verbose_name='Card image'),
        ),
    ]
