# Generated by Django 4.0.6 on 2022-08-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cards_cardimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='imageURL',
            field=models.URLField(default=False, verbose_name='Image source'),
        ),
    ]
